### ISSUE TITLE
Merged File not Created and No Errors Thrown

### ISSUE THREAD

**Issue by clsteel** [cowzendux/mergeAllSPSScases#1]
I am new to using Python in SPSS and am trying to use this code but I can't figure out why it's not doing anything. When I run it there are no errors thrown in the log (even if I don't turn off the printback). 

I'm running SPSS 24 on Windows. I tried different iterations of the filepath, with double slashes and single slashes forwards and backwards, all to no avail. The files I'm trying to merge are very simple single case datasets all with matching variable types and lengths so I don't have any reason to believe it's something with the data or a strange nuance with the code itself. Assume I'm as novice to Python as they come so maybe I am missing something extremely obvious? Can anyone help? I'm attaching my SPSS output file.

[OUTPUT.pdf](https://github.com/cowzendux/mergeAllSPSScases/files/6012432/OUTPUT.pdf)

**Comment by cowzendux** [comment]
The program itself is a macro. Running the syntax defines the mergeAllAPSScases function, but doesn't actually do anything else. After the syntax is run, you need to use a separate program to actually issue the command within a python block. Usually I save the macro to its own file and then insert it using an "include" statement at the top of the program that is supposed to do the merging. Below is an extension of the example I have on front page with some extra code to show you what the full program might look like.

-----

insert file = "C:/Users/jd4nb/Dropbox/Art project/Data/mergeAllSPSScases.sps".

begin program python.
mergeAllSPSScases(indir = "C:/Users/jd4nb/Dropbox/Art project/Data/Raw",
mergename = "Merged art data.sav",
outdir = "C:/Users/jd4nb/Dropbox/Art project/Data/Final",
sourceVar = "School",
alignFormats = True)
end program python.

-----

Hope this helps - if your problem is something different let me know.

**Comment by clsteel** [comment]
Ah of course! That's exactly the piece I needed to understand. Thank you so much for your help!
